SELECT * FROM jsoren.PUBLIC_USER_INFORMATION MINUS SELECT * FROM VIEW_USER_INFORMATION;
SELECT * FROM jsoren.PUBLIC_PHOTO_INFORMATION MINUS SELECT * FROM VIEW_PHOTO_INFORMATION;
SELECT * FROM jsoren.PUBLIC_TAG_INFORMATION MINUS SELECT * FROM VIEW_TAG_INFORMATION;
SELECT * FROM jsoren.PUBLIC_EVENT_INFORMATION MINUS SELECT * FROM VIEW_EVENT_INFORMATION;